@ 'D:\2TDSPB\lari-na-fiap2\050924\SCRIPT_MODELO_PEDIDO.SQL';

INSERT INTO PAIS SELECT * FROM PF1788.PAIS;
INSERT INTO ESTADO SELECT * FROM PF1788.ESTADO;
INSERT INTO CIDADE SELECT * FROM PF1788.CIDADE;
INSERT INTO TIPO_ENDERECO SELECT * FROM PF1788.TIPO_ENDERECO;
INSERT INTO CLIENTE SELECT * FROM PF1788.CLIENTE;
INSERT INTO ENDERECO_CLIENTE SELECT * FROM PF1788.ENDERECO_CLIENTE;
INSERT INTO USUARIO SELECT * FROM PF1788.USUARIO;
INSERT INTO VENDEDOR SELECT * FROM PF1788.VENDEDOR;
INSERT INTO PRODUTO SELECT * FROM PF1788.PRODUTO;
INSERT INTO PRODUTO_COMPOSTO SELECT * FROM PF1788.PRODUTO_COMPOSTO;
INSERT INTO TIPO_MOVIMENTO_ESTOQUE SELECT * FROM PF1788.TIPO_MOVIMENTO_ESTOQUE;
INSERT INTO ESTOQUE SELECT * FROM PF1788.ESTOQUE;
INSERT INTO ESTOQUE_PRODUTO SELECT * FROM PF1788.ESTOQUE_PRODUTO;
INSERT INTO MOVIMENTO_ESTOQUE SELECT * FROM PF1788.MOVIMENTO_ESTOQUE;
INSERT INTO CLIENTE_VENDEDOR SELECT * FROM PF1788.CLIENTE_VENDEDOR;
INSERT INTO PEDIDO SELECT * FROM PF1788.PEDIDO;
INSERT INTO HISTORICO_PEDIDO SELECT * FROM PF1788.HISTORICO_PEDIDO;
INSERT INTO ITEM_PEDIDO SELECT * FROM PF1788.ITEM_PEDIDO;


ALTER TABLE CIDADE MODIFY NOM_CIDADE VARCHAR2(40);
ALTER TABLE PEDIDO ADD STATUS VARCHAR(30);

SELECT * FROM CLIENTE;